---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-client
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false" # 애플리케이션 제거 후 데이터 유지할라면 true로 변경
mountOptions:
  - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs
spec:
  # storageClassName: "" # 선언해주지 말자
  accessModes: # AccessModes
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi # 1GB 요청
---
apiVersion: v1
kind: Pod
metadata:
  name: pvc-httpd
spec:
  containers:
    - name: pvc-httpd
      image: httpd
      volumeMounts:
        - name: nfs
          mountPath: /usr/local/apache2/htdocs
  volumes:
    - name: nfs
      persistentVolumeClaim:
        claimName: pvc-nfs

