# 동적 프로비저닝이 안되기 때문에 선언해서 사용함
# volumeBindingMode: pvc를 사용하는 pod가 실제 생성되기 전까지 바인딩, 프로비저닝 대기
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer  

# 로컬 pv는 동적 볼륨 프로비저너를 지원하지 않는다. == pv를 직접 만들고 pvc를 만들어야 한다.
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /tmp/test
  nodeAffinity:  # 특정 노드를 지정하여 이를 활용하는 파드가 올바른 노드로 스케줄링 할 수 있도록
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ip-70-0-1-225  # 노드 명
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
spec:
  storageClassName: local-storage
  volumeName: local-pv # 앞서 생성한 pv와 바운드 해주어야 함
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi # pv랑 용량매칭이 동일해야함
---
apiVersion: v1
kind: Pod
metadata:
  name: pvc-httpd
spec:
  containers:
    - name: pvc-httpd
      image: httpd
      volumeMounts:
        - name: local-pv-test
          mountPath: /usr/local/apache2/htdocs
  volumes:
    - name: local-pv-test
      persistentVolumeClaim:
        claimName: local-pvc

