# 베이스 이미지 설정
FROM amazonlinux:2023

RUN yum install -y httpd
# RUN echo im $(cat /etc/hostname) > /var/www/html/index.html
RUN 
# 호스트의 웹 사이트 디렉토리를 컨테이너 내부로 복사
# COPY ./website/ /usr/local/apache2/htdocs/

# 컨테이너가 사용할 포트 노출
EXPOSE 80

# 볼륨 마운트 지정
# VOLUME /usr/local/apache2/htdocs

# Apache HTTP Server 실행
# CMD ["httpd-foreground"]
CMD ["/usr/sbin/httpd","-D","FOREGROUND"]