---
apiVersion: v1
kind: Pod
metadata:
  name: count
spec:
  volumes:
    - name: html  # mount할 볼륨 명
      emptyDir: {}
  containers:  
    - image: ash0927/count:latest
      name: html-generator
      volumeMounts:
        - name: html  # volumes에서 선언 한 볼륨 이름 
          mountPath: /var/htdocs # Container 내에서 볼륨과 공유 할 경로 (count하며 갱신되는 html주소)
    - image: httpd
      name: web-server
      volumeMounts:
      - name: html  # volumes에서 선언 한 볼륨 이름 
        mountPath: /usr/local/apache2/htdocs # apache가 html을 읽어오는 경로
        readOnly: true
      ports:
      - containerPort: 80
        protocol: TCP