---
apiVersion: v1
kind: Pod
metadata:
  name: hostpath-test
spec:
  containers:
    - name: http-hostpath
      image: httpd
      volumeMounts:
        - name: html
          mountPath: /usr/local/apache2/htdocs
          readOnly: true
      ports:
        - containerPort: 80
          protocol: TCP
  volumes:
    - name: html
      hostPath:
        path: /var/test/
        type: Directory