apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  completions: 5 # 목표 완료 파드 개수
  parallelism: 3 # 동시 실행 가능 파드 개수
  template:
    spec:
      containers:
      - name: pi
        image: perl:5.34.0
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4

