---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app.kubernetes.io/name: MyApp
spec:
  containers:
  - name: myapp-container
    image: busybox:1.28
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
  initContainers:
  - name: init-tomcat
    image: busybox:1.28
    command: ['sh', '-c', "until nslookup tomcat-ajp-svc.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]
---
apiVersion: v1
kind: Pod
metadata:
  name: apache
  labels:
    app: apache
spec:
  containers:
  - name: apache
    image: ash0927/httpd-connector:1
    env:
      - name: tomcat_svc
        value: tomcat-ajp-svc.default.svc.cluster.local
    ports:
      - containerPort: 80