apiVersion: v1
kind: Service
metadata:
  name: tomcat-ajp-svc
spec:
  type: NodePort
  # sessionAffinity: ClientIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: ajp
      port: 8009
      targetPort: 8009
  selector:
    app: tomcat-ajp
---
apiVersion: v1
kind: Pod
metadata:
  name: tomcat-ajp
  labels:
    app: tomcat-ajp
spec:
  containers:
    - name: tomcat
      image: ash0927/tomcat-ajp
      ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8009
          protocol: ajp