---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-cm
  namespace: default
data:
  hello: imfine
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
  namespace: default
data:
  log_level: INFO
