---
apiVersion: v1
kind: Namespace
metadata:
  name: limit-space
---
apiVersion: v1
kind: LimitRange
metadata:
  name: container-limit
  namespace: limit-space
spec:
  limits:
    - type: Container
      max:
        cpu: 500m
        memory: 1Gi
      min:
        cpu: 10m
        memory: 50Mi
      default:  # 기본 제한
        cpu: 400m
        memory: 800Mi
      defaultRequest: # 기본 요구사항
        cpu: 250m
        memory: 250Mi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: pod-limit
  namespace: limit-space
spec:
  limits:
    - type: Pod  # 멀티 컨테이너의 경우를 위해 pod 수준 제약이 필요함
      max:
        cpu: 2 # 2 core
        memory: 2Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: storage-limit
  namespace: limit-space
spec:
  limits:
    - type: PersistentVolumeClaim
      max:
        storage: 2Gi
      min:
        storage: 500Mi