---
apiVersion: v1
kind: Pod
metadata:
  name: multi
  labels:
    app: nginx-redis
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
  - name: redis
    image: redis