---
apiVersion: v1
kind: Pod
metadata:
  name: apache
  labels:
    app.kubernetes.io/name: MyApp
spec:
  containers:
  - name: apache
    image: ash0927/httpd-connector:2
    ports:
      - containerPort: 80
  initContainers:
  - name: init-tomcat
    image: busybox:1.28
    # 같은 k8s 네트워크 대역에 있으니 도메인 정보를 확인할 수 있다.
    # 그걸 응용하여 도메인 정보가 확인될 때까지 컨테이너의 상태를 유지한다.
    command: ['sh', '-c', "until nslookup tomcat-ajp-svc.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]