apiVersion: v1
kind: Pod
metadata:
  name: busyboxs
  namespace: limit-space
spec:
  containers:
  - args:
    - -c
    - while true; do echo hello from cnt01; sleep 10;done
    command:
    - /bin/sh
    image: busybox:1.28
    name: custom-range-limit
    resources:
      limits:
        cpu: 499m
        memory: 150Mi
      requests:
        cpu: 100m
        memory: 50Mi
  - args:
    - -c
    - while true; do echo hello from cnt02; sleep 10;done
    command:
    - /bin/sh
    image: busybox:1.28
    name: min-limit
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
  - args:
    - -c
    - while true; do echo hello from cnt03; sleep 10;done
    command:
    - /bin/sh
    image: busybox:1.28
    name: max-limit
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
  - args:
    - -c
    - while true; do echo hello from cnt04; sleep 10;done
    command:
    - /bin/sh
    image: busybox:1.28
    name: default-limit