---
apiVersion: v1
kind: Pod
metadata:
  name: secret-test
spec:
  containers:
  - name: secret-test
    image: httpd
    env:
    - name: SECRET_USER
      valueFrom:
       secretKeyRef:
         name: secret-test
         key: id
    - name: SECRET_PASSWORD
      valueFrom:
       secretKeyRef:
         name: secret-test
         key: pw