apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  # the name here should match the name of the Service
  name: my-service
subsets:
  - addresses:
      - ip: 223.130.195.95   #naver.com IP 주소
      - ip: 199.201.110.204  #www.malware-traffic-analysis.net IP 주소
    ports:
      - port: 80
